### ISSUE TITLE
Unknown error when ChromeLauncher.launch() in worker thread

### ISSUE THREAD

**Issue by archvlad** [GoogleChrome/chrome-launcher#306]
**OS:** Windows 11
**Node.js:** v16.20.0

#### test.js
```
const Piscina = require("piscina");

const piscina = new Piscina({
    filename: "script.js",
});

piscina.run();

```
#### script.js
```
const ChromeLauncher = require("chrome-launcher");
const puppeteer = require("puppeteer");
async function run() {
    chrome = await ChromeLauncher.launch();
    browser = await puppeteer.connect({
        browserURL: `http://127.0.0.1:${chrome.port}`,
        defaultViewport: null,
    });
    let [page] = await browser.pages();
    await page.goto("https://google.com/");
}

module.exports = run;

```

After running `node test` I get this stack trace with unknown error:
```
Error
    at new LauncherError (node_modules\chrome-launcher\dist\utils.js:26:22)
    at new ChromeNotInstalledError (node_modules\chrome-launcher\dist\utils.js:57:9)
    at Launcher.launch (node_modules\chrome-launcher\dist\chrome-launcher.js:189:23)
    at Object.launch (node_modules\chrome-launcher\dist\chrome-launcher.js:35:20)
    at run (script.js:4:35)
    at node_modules\piscina\dist\src\worker.js:141:32
```

**Comment by archvlad** [comment]
If I set chromePath in options to ChromeLauncher.launch() it works fine, but I don't know why.
```
const ChromeLauncher = require("chrome-launcher");
const puppeteer = require("puppeteer");
async function run() {
    chrome = await ChromeLauncher.launch({
        chromePath:
            "C:\\\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
    });
    browser = await puppeteer.connect({
        browserURL: `http://127.0.0.1:${chrome.port}`,
        defaultViewport: null,
    });
    let [page] = await browser.pages();
    await page.goto("https://google.com/");
}

module.exports = run;

```

**Comment by archvlad** [comment]
If I set chromePath in options to ChromeLauncher.launch() it works fine, but I don't know why.

```
const ChromeLauncher = require("chrome-launcher");
const puppeteer = require("puppeteer");
async function run() {
    chrome = await ChromeLauncher.launch({
        chromePath:
            "C:\\\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
    });
    browser = await puppeteer.connect({
        browserURL: `http://127.0.0.1:${chrome.port}`,
        defaultViewport: null,
    });
    let [page] = await browser.pages();
    await page.goto("https://google.com/");
}

module.exports = run;

```
