### ISSUE TITLE
finder: Failing to find google-chrome binary on centos 7

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/chrome-launcher#54]
Reported by @jayflux

```
CHROME_PATH=/usr/bin/google-chrome
NODE_EXTRA_CA_CERTS=/etc/pki/tls/certs/ca-bundle.crt
_=/usr/bin/env
[developer@sounds-performance sounds-performance]$ sudo -E node index.js 
which: no chromium-browser in (/sbin:/bin:/usr/sbin:/usr/bin)
which: no chromium in (/sbin:/bin:/usr/sbin:/usr/bin)
{ Error: connect ECONNREFUSED 127.0.0.1:33429
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 33429 }
[developer@sounds-performance sounds-performance]$ 
```

1. `google-chrome` installed via YUM on centos 7. chrome-finder is failing to locate it. 
1. and the explicit `CHROME_PATH` setting doesn't seem to fix things.

**Comment by Jayflux** [comment]
If it helps my google chrome installation step was...
```
# Install Google Chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
RUN yum install ./google-chrome-stable_current_*.rpm -y
RUN rm google-chrome-stable_current_*.rpm
```

I've set `CHROME_PATH=/usr/bin/google-chrome`

And then i followed https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#using-programmatically

**Comment by paulirish** [comment]
@Jayflux got a dockerfile or image recommendation that I can use to reproduce this centos setup?

**Comment by Jayflux** [comment]
Hey @paulirish i wasn't ignoring you.
I've created a testcase project for you all to try out.
https://github.com/Jayflux/lighthouse-testcase

This should help you with debugging

**Comment by Jayflux** [comment]
Managed to fix it.
It was this issue,  https://github.com/GoogleChrome/chrome-launcher/issues/6#issuecomment-341491690

**Comment by mariusJar** [comment]
Also had
which: no chromium-browser in (/sbin:/bin:/usr/sbin:/usr/bin)
which: no chromium in (/sbin:/bin:/usr/sbin:/usr/bin)

"sudo yum install -y chromium" helped for me
