### ISSUE TITLE
Launch Error on travis-ci

### ISSUE THREAD

**Issue by maple3142** [GoogleChrome/chrome-launcher#97]
In [Build #70](https://travis-ci.org/maple3142/Blog/builds/353838783), I get a error message:
```
Launch Error: { Error: connect ECONNREFUSED 127.0.0.1:41697
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  [stack]: 'Error: connect ECONNREFUSED 127.0.0.1:41697\n    at Object._errnoException (util.js:1022:11)\n    at _exceptionWithHostPort (util.js:1044:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)',
  [message]: 'connect ECONNREFUSED 127.0.0.1:41697',
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 41697 }
```
But this doesn't happen on my computer.

script: https://github.com/maple3142/Blog/blob/30fa93f43ec08a5f83b26822af7b5e4266d0b0df/lighthouse.js
.travis.yml: https://github.com/maple3142/Blog/blob/30fa93f43ec08a5f83b26822af7b5e4266d0b0df/.travis.yml

**Comment by IgnusG** [comment]
I'm getting the same error trying to launch from inside a gulp script.
```
Error: connect ECONNREFUSED 127.0.0.1:3001
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)
```
I tried setting the port to something I knew wasn't blocked, yet it failed anyway.
